const NEWTECHNOLOGIES = [
  {name:"Alexa for Business"},
  {name:"Amazon API Gateway"},
  {name:"Amazon AppFlow"},
  {name:"Amazon AppStream 2.0"},
  {name:"Amazon Athena"},
  {name:"Amazon Augmented AI"},
  {name:"Amazon Aurora"},
  {name:"Amazon Braket"},
  {name:"Amazon Chime"},
  {name:"Amazon CloudFront"},
  {name:"Amazon CloudSearch"},
  {name:"Amazon CloudWatch"},
  {name:"Amazon CodeGuru"},
  {name:"Amazon Cognito"},
  {name:"Amazon Comprehend"},
  {name:"Amazon Connect"},
  {name:"Amazon Corretto"},
  {name:"Amazon Detective"},
  {name:"Amazon DevOps Guru"},
  {name:"Amazon DocumentDB"},
  {name:"Amazon DynamoDB"},
  {name:"Amazon EC2"},
  {name:"Amazon EC2 Auto Scaling"},
  {name:"Amazon Elastic Block Store (EBS)"},
  {name:"Amazon Elastic Container Registry (ECR)"},
  {name:"Amazon Elastic Container Service (ECS)"},
  {name:"Amazon Elastic File System (EFS)"},
  {name:"Amazon Elastic Inference"},
  {name:"Amazon Elastic Kubernetes Service (EKS)"},
  {name:"Amazon Elastic Transcoder"},
  {name:"Amazon ElastiCache"},
  {name:"Amazon EMR"},
  {name:"Amazon EventBridge"},
  {name:"Amazon FinSpace"},
  {name:"Amazon Forecast"},
  {name:"Amazon Fraud Detector"},
  {name:"Amazon FreeRTOS"},
  {name:"Amazon FSx"},
  {name:"Amazon GameLift"},
  {name:"Amazon GuardDuty"},
  {name:"Amazon HealthLake"},
  {name:"Amazon Honeycode"},
  {name:"Amazon Inspector"},
  {name:"Amazon Interactive Video Service"},
  {name:"Amazon Kendra"},
  {name:"Amazon Keyspaces (for Apache Cassandra)"},
  {name:"Amazon Kinesis"},
  {name:"Amazon Kinesis Video Streams"},
  {name:"Amazon Lex"},
  {name:"Amazon Lightsail"},
  {name:"Amazon Location Service"},
  {name:"Amazon Lookout for Equipment"},
  {name:"Amazon Lookout for Metrics"},
  {name:"Amazon Lookout for Vision"},
  {name:"Amazon Lumberyard"},
  {name:"Amazon Macie"},
  {name:"Amazon Managed Blockchain"},
  {name:"Amazon Managed Grafana"},
  {name:"Amazon Managed Service for Prometheus"},
  {name:"Amazon Managed Streaming for Apache Kafka (MSK)"},
  {name:"Amazon Managed Workflows for Apache Airflow (MWAA)"},
  {name:"Amazon MemoryDB for Redis"},
  {name:"Amazon Monitron"},
  {name:"Amazon MQ"},
  {name:"Amazon Neptune"},
  {name:"Amazon Nimble Studio"},
  {name:"Amazon OpenSearch Service (successor to Amazon Elasticsearch Service)"},
  {name:"Amazon Personalize"},
  {name:"Amazon Pinpoint"},
  {name:"Amazon Polly"},
  {name:"Amazon Quantum Ledger Database (QLDB)"},
  {name:"Amazon QuickSight"},
  {name:"Amazon RDS"},
  {name:"Amazon RDS on VMware"},
  {name:"Amazon Redshift"},
  {name:"Amazon Rekognition"},
  {name:"Amazon Route 53"},
  {name:"Amazon S3 Glacier"},
  {name:"Amazon SageMaker"},
  {name:"Amazon SageMaker Ground Truth"},
  {name:"Amazon Simple Email Service (SES)"},
  {name:"Amazon Simple Notification Service (SNS)"},
  {name:"Amazon Simple Queue Service (SQS)"},
  {name:"Amazon Simple Storage Service (S3)"},
  {name:"Amazon Sumerian"},
  {name:"Amazon Textract"},
  {name:"Amazon Timestream"},
  {name:"Amazon Transcribe"},
  {name:"Amazon Translate"},
  {name:"Amazon VPC"},
  {name:"Amazon WorkDocs"},
  {name:"Amazon WorkLink"},
  {name:"Amazon WorkMail"},
  {name:"Amazon WorkSpaces"},
  {name:"Apache MXNet on AWS"},
  {name:"AWS Amplify"},
  {name:"AWS App Mesh"},
  {name:"AWS App Runner"},
  {name:"AWS App2Container"},
  {name:"AWS Application Discovery Service"},
  {name:"AWS AppSync"},
  {name:"AWS Artifact"},
  {name:"AWS Audit Manager"},
  {name:"AWS Auto Scaling"},
  {name:"AWS Backup"},
  {name:"AWS Batch"},
  {name:"AWS Budgets"},
  {name:"AWS Certificate Manager"},
  {name:"AWS Chatbot"},
  {name:"AWS Cloud Control API"},
  {name:"AWS Cloud Development Kit (CDK)"},
  {name:"AWS Cloud Map"},
  {name:"AWS Cloud WAN (Preview)"},
  {name:"AWS Cloud9"},
  {name:"AWS CloudFormation"},
  {name:"AWS CloudHSM"},
  {name:"AWS CloudShell"},
  {name:"AWS CloudTrail"},
  {name:"AWS CodeArtifact"},
  {name:"AWS CodeBuild"},
  {name:"AWS CodeCommit"},
  {name:"AWS CodeDeploy"},
  {name:"AWS CodePipeline"},
  {name:"AWS CodeStar"},
  {name:"AWS Command Line Interface (CLI)"},
  {name:"AWS Compute Optimizer"},
  {name:"AWS Config"},
  {name:"AWS Control Tower"},
  {name:"AWS Copilot"},
  {name:"AWS Cost and Usage Report"},
  {name:"AWS Cost Explorer"},
  {name:"AWS Data Exchange"},
  {name:"AWS Data Pipeline"},
  {name:"AWS Database Migration Service (DMS)"},
  {name:"AWS DataSync"},
  {name:"AWS Deep Learning AMIs"},
  {name:"AWS Deep Learning Containers"},
  {name:"AWS DeepComposer"},
  {name:"AWS DeepLens"},
  {name:"AWS DeepRacer"},
  {name:"AWS Device Farm"},
  {name:"AWS Direct Connect"},
  {name:"AWS Directory Service"},
  {name:"AWS Distro for OpenTelemetry"},
  {name:"AWS Elastic Beanstalk"},
  {name:"AWS Elemental Appliances & Software"},
  {name:"AWS Elemental MediaConnect"},
  {name:"AWS Elemental MediaConvert"},
  {name:"AWS Elemental MediaLive"},
  {name:"AWS Elemental MediaPackage"},
  {name:"AWS Elemental MediaStore"},
  {name:"AWS Elemental MediaTailor"},
  {name:"AWS Fargate"},
  {name:"AWS Fault Injection Simulator"},
  {name:"AWS Firewall Manager"},
  {name:"AWS Global Accelerator"},
  {name:"AWS Glue"},
  {name:"AWS Ground Station"},
  {name:"AWS Identity and Access Management"},
  {name:"AWS Inferentia"},
  {name:"AWS IoT 1-Click"},
  {name:"AWS IoT Analytics"},
  {name:"AWS IoT Button"},
  {name:"AWS IoT Core"},
  {name:"AWS IoT Device Defender"},
  {name:"AWS IoT Device Management"},
  {name:"AWS IoT EduKit"},
  {name:"AWS IoT Events"},
  {name:"AWS IoT FleetWise (Preview)"},
  {name:"AWS IoT Greengrass"},
  {name:"AWS IoT RoboRunner (Preview)"},
  {name:"AWS IoT SiteWise"},
  {name:"AWS IoT Things Graph"},
  {name:"AWS IoT TwinMaker (Preview)"},
  {name:"AWS Key Management Service (KMS)"},
  {name:"AWS Lake Formation"},
  {name:"AWS Lambda"},
  {name:"AWS Launch Wizard"},
  {name:"AWS License Manager"},
  {name:"AWS Mainframe Modernization (Preview)"},
  {name:"AWS Managed Services"},
  {name:"AWS Management Console"},
  {name:"AWS Management Console Mobile Application"},
  {name:"AWS Migration Hub"},
  {name:"AWS Network Firewall"},
  {name:"AWS OpsWorks"},
  {name:"AWS Organizations"},
  {name:"AWS Outposts"},
  {name:"AWS Panorama"},
  {name:"AWS Partner Device Catalog"},
  {name:"AWS Personal Health Dashboard"},
  {name:"AWS Private 5G"},
  {name:"AWS PrivateLink"},
  {name:"AWS Proton"},
  {name:"AWS Resilience Hub"},
  {name:"AWS Resource Access Manager"},
  {name:"AWS RoboMaker"},
  {name:"AWS Secrets Manager"},
  {name:"AWS Security Hub"},
  {name:"AWS Server Migration Service (SMS)"},
  {name:"AWS Serverless Application Repository"},
  {name:"AWS Service Catalog"},
  {name:"AWS Shield"},
  {name:"AWS Single Sign-On (SSO)"},
  {name:"AWS Snow Family"},
  {name:"AWS Step Functions"},
  {name:"AWS Storage Gateway"},
  {name:"AWS Systems Manager"},
  {name:"AWS Tools and SDKs"},
  {name:"AWS Transfer Family"},
  {name:"AWS Transit Gateway"},
  {name:"AWS Trusted Advisor"},
  {name:"AWS VPN"},
  {name:"AWS WAF"},
  {name:"AWS Wavelength"},
  {name:"AWS Well-Architected Tool"},
  {name:"AWS X-Ray"},
  {name:"CloudEndure Disaster Recovery"},
  {name:"CloudEndure Migration"},
  {name:"Elastic Load Balancing (ELB)"},
  {name:"Migration Evaluator (formerly TSO Logic)"},
  {name:"PyTorch on AWS"},
  {name:"Red Hat OpenShift Service on AWS"},
  {name:"Reserved Instance (RI) Reporting"},
  {name:"Savings Plans"},
  {name:"TensorFlow on AWS"},
  {name:"VMware Cloud on AWS"},

  {name:"Angular"},
  {name:"Asset"},
  {name:"Asset Lifecycle Management"},
  {name:"Big Data Solutions Architect"},
  {name:"Cash and Treasury"},
  {name:"Cloud Computing"},
  {name:"Cloud Financials Architect"},
  {name:"Cloud HCM"},
  {name:"Cloud Infrastructure Architect"},
  {name:"Cloud Operations Engineer"},
  {name:"Cloud SCM/Procurement Architect"},
  {name:"Cloud Solutions Architect"},
  {name:"Consultant - Functional"},
  {name:"Consultant - Technical"},
  {name:"Consultant Administrator"},
  {name:"Corporate Performance Management"},
  {name:"DevOps Engineer"},
  {name:"Developer / Programmer"},
  {name:"Django"},
  {name:"E-Business Suite Specialist"},
  {name:"Einstein Analytics"},
  {name:"Elastic Load Balancing"},
  {name:"Financial Control and Reporting"},
  {name:"Financials Common Modules"},
  {name:"Herok"},
  {name:"Html"},
  {name:"Internet Expenses"},
  {name:"Internet of things"},
  {name:"Master data Management"},
  {name:"MongoDB"},
  {name:"Mulesoft"},
  {name:"Mysql"},
  {name:"NodeJS"},
  {name:"Oracle Advanced Collection"},
  {name:"Oracle Advanced Global Intercompany System"},
  {name:"Oracle Advanced Pricing"},
  {name:"Oracle Applications Developer"},
  {name:"Oracle Approvals Management"},
  {name:"Oracle Asset tracking"},
  {name:"Oracle Assets"},
  {name:"Oracle Bill Presentment Architecture"},
  {name:"Oracle Bills Of Materials"},
  {name:"Oracle Cash Management"},
  {name:"Oracle Compensation and Benefits Management"},
  {name:"Oracle Configurator"},
  {name:"Oracle Configure to Order"},
  {name:"Oracle Configuring Reporting and System Administrator"},
  {name:"Oracle Cost Management"},
  {name:"Oracle Credit Management"},
  {name:"Oracle E-Business Tax"},
  {name:"Oracle E-Business Tax reporting"},
  {name:"Oracle Engineering"},
  {name:"Oracle Enterprise Asset Management"},
  {name:"Oracle Enterprise Performance"},
  {name:"Oracle Enterprise Planning and Budgeting"},
  {name:"Oracle Enterprise and Workforce Management"},
  {name:"Oracle Fast Formula"},
  {name:"Oracle Financial Consolidation Hub"},
  {name:"Oracle Financial Services"},
  {name:"Oracle Financial Services Accounting Hub"},
  {name:"Oracle Financials"},
  {name:"Oracle Financials RXi Reports Administration"},
  {name:"Oracle Financials for Asia/Pacific"},
  {name:"Oracle Financials for Europe"},
  {name:"Oracle Financials for India"},
  {name:"Oracle Financials for the Americas"},
  {name:"Oracle Flow Manufacturing"},
  {name:"Oracle Fusion Configurator"},
  {name:"Oracle General Ledger"},
  {name:"Oracle Grants Accounting"},
  {name:"Oracle Human Resources"},
  {name:"Oracle Install Base"},
  {name:"Oracle Integrating Oracle Transportation management with EBS"},
  {name:"Oracle Internal Controls Manager"},
  {name:"Oracle Internet Expenses"},
  {name:"Oracle Inventory"},
  {name:"Oracle Labor Distribution"},
  {name:"Oracle Landed Cost Management"},
  {name:"Oracle Learning Management"},
  {name:"Oracle Lease and Finance Management"},
  {name:"Oracle Loans"},
  {name:"Oracle Loans"},
  {name:"Oracle Manufacturing"},
  {name:"Oracle Manufacturing Execution System for Discrete Manufacturing"},
  {name:"Oracle Manufacturing Execution System for Process Manufacturing"},
  {name:"Oracle Manufacturing Operations Center"},
  {name:"Oracle Manufacturing: Subcontracting"},
  {name:"Oracle Mobile Supply Chain Application"},
  {name:"Oracle Order Management"},
  {name:"Oracle Payables"},
  {name:"Oracle Payments"},
  {name:"Oracle Payroll"},
  {name:"Oracle Performance Management"},
  {name:"Oracle Portfolio Analysis"},
  {name:"Oracle Process Manufacturing Cost Management"},
  {name:"Oracle Process Manufacturing Mobile Supply Chain Applications for Process Manufacturing"},
  {name:"Oracle Process Manufacturing Quality Management"},
  {name:"Oracle Process Manufacturing Quality Management"},
  {name:"Oracle Process Manufacturing Regulatory Management"},
  {name:"Oracle Process Manufacturing System Administration"},
  {name:"Oracle Product Information Management"},
  {name:"Oracle Profitability Manager"},
  {name:"Oracle Project Billing"},
  {name:"Oracle Project Costing"},
  {name:"Oracle Project Fundamentals"},
  {name:"Oracle Project Management"},
  {name:"Oracle Project Resource Management"},
  {name:"Oracle Property Manager"},
  {name:"Oracle Public Sector Budgeting"},
  {name:"Oracle Public Sector Financials"},
  {name:"Oracle Purchasing"},
  {name:"Oracle Quality"},
  {name:"Oracle Receivables"},
  {name:"Oracle Receivables: Golden Tax Adapter for Mainland China"},
  {name:"Oracle Release Management"},
  {name:"Oracle Self-Service Human Resources"},
  {name:"Oracle Shipping Execution"},
  {name:"Oracle Shop Floor Management"},
  {name:"Oracle Site Hub"},
  {name:"Oracle Sourcing"},
  {name:"Oracle Subledger Accounting"},
  {name:"Oracle Succession Planning"},
  {name:"Oracle Supplier Management"},
  {name:"Oracle Time and Labor"},
  {name:"Oracle Transfer Pricing"},
  {name:"Oracle Treasury"},
  {name:"Oracle U.S Federal Financials"},
  {name:"Oracle Warehouse Management"},
  {name:"Oracle Work in Process"},
  {name:"Oracle Workforce Sourcing and Talent Management"},
  {name:"Oracle iAssets"},
  {name:"Oracle iProcurement"},
  {name:"Oracle iReceivables"},
  {name:"Oracle iRecruitment"},
  {name:"Oracle iSupplier Portal"},
  {name:"Phython"},
  {name:"Postgres"},
  {name:"Qui"},
  {name:"React"},
  {name:"React Native"},
  {name:"Ruby"},
  {name:"Ruby on rails"},
  {name:"Run AWS services on-premises"},
  {name:"Salesforce"},
  {name:"Salesforce B2B Commerce"},
  {name:"Salesforce B2C Commerce"},
  {name:"Salesforce CPQ"},
  {name:"Salesforce Commerce Cloud"},
  {name:"Salesforce Communities"},
  {name:"Salesforce Data Management platform"},
  {name:"Salesforce Education Cloudc"},
  {name:"Salesforce Field Service Lightning"},
  {name:"Salesforce Financial Services Cloud"},
  {name:"Salesforce Health Cloud"},
  {name:"Salesforce Marketing Automation"},
  {name:"Salesforce Marketing Cloud"},
  {name:"Salesforce Philanthropy Cloud"},
  {name:"Salesforce Platform"},
  {name:"Salesforce Sales Cloud"},
  {name:"Salesforce Sales Cloud Einstein"},
  {name:"Salesforce Service Cloud"},
  {name:"Security Engineer"},
  {name:"Solution Architect"},
  {name:"Technical Architect"},
  {name:"VMware Cloud on AWS"},
  {name:"Virtual machines"},
  {name:"Azure Kubernetes Service (AKS)"},
  {name:"Service Fabric"},
  {name:"App Service"},
  {name:"Quickly create powerful cloud apps for web and mobile"},
  {name:"Container Instances"},
  {name:"Batch"},
  {name:"SQL Server on Virtual Machines"},
  {name:"Cloud Services"},
  {name:"SAP HANA on Azure Large Instances"},
  {name:"Azure Functions"},
  {name:"Virtual Machine Scale Sets "},
  {name:"Web Apps"},
  {name:"Mobile Apps"},
  {name:"API Apps"},
  {name:"Easily build and consume Cloud APIs"},
  {name:"Linux Virtual Machines"},
  {name:"Windows Virtual Desktop"},
  {name:"Azure CycleCloud"},
  {name:"Azure VMware Solution by CloudSimple"},
  {name:"Azure Dedicated Host"},
  {name:"Azure Spring Cloud"},
  {name:"Cloud Run"},
  {name:"Cloud Functions"},
  {name:"Compute Engine"},
  {name:"Kubernetes Engine (GKE)"},
  {name:"App Engine"},
  {name:"Bare Metal Solution"},
  {name:"Preemptible VMs"},
  {name:"Shielded VMs"},
  {name:"Sole-tenant nodes"},
  {name:"Cloud Filestore"},
  {name:"Cloud Storage"},
  {name:"Persistent Disk"},
  {name:"Local SSD"},
  {name:"Cloud"},
  {name:"Bigtable"},
  {name:"Firestore"},
  {name:"Memorystore"},
  {name:"Spanner"},
  {name:"SQL"},
  {name:"BigQuery"},
  {name:"BigQuery BI Engine"},
  {name:"BigQuery ML"},
  {name:"Cloud Composer"},
  {name:"Cloud Data Fusion"},
  {name:"Cloud Dataflow"},
  {name:"Cloud Dataprep"},
  {name:"Cloud Dataproc"},
  {name:"Cloud Pub/Sub"},
  {name:"Data Catalog"},
  {name:"Data Studio"},
  {name:"Looker"},
  {name:"Anthos"},
  {name:"Anthos GKE"},
  {name:"Anthos Config Management"},
  {name:"Anthos Service Mesh"},
  {name:"Cloud Run for Anthos"},
  {name:"GCP Marketplace for Anthos"},
  {name:"Migrate for Anthos"},
  {name:"Operations"},
  {name:"Cloud Build"},
  {name:"Traffic Director"},
  {name:"Apigee API Management"},
  {name:"AI Hub"},
  {name:"AI Platform Data Labeling"},
  {name:"AI Platform Deep Learning VMs"},
  {name:"AI Platform Deep Learning Containers"},
  {name:"AI Platform Notebooks"},
  {name:"AI Platform Pipelines"},
  {name:"AI Platform Predictions"},
  {name:"AI Platform Training"},
  {name:"AI Platform"},
  {name:"AutoML Natural Language"},
  {name:"AutoML Tables"},
  {name:"AutoML Translation"},
  {name:"AutoML Video Intelligence"},
  {name:"AutoML Vision"},
  {name:"Cloud Natural Language API"},
  {name:"Cloud Speech-To-Text API"},
  {name:"Cloud Talent Solutions API"},
  {name:"Cloud Text-To-Speech API"},
  {name:"Cloud TPU"},
  {name:"Cloud Translation API"},
  {name:"Cloud Video Intelligence API"},
  {name:"Cloud Vision API"},
  {name:"Contact Center AI"},
  {name:"Dialogflow"},
  {name:"Document AI"},
  {name:"Explainable AI"},
  {name:"Recommendations AI"},
  {name:"Vision Product Search"},
  {name:"Carrier Peering"},
  {name:"Direct Peering"},
  {name:"Dedicated Interconnect"},
  {name:"Partner Interconnect"},
  {name:"Cloud Armor"},
  {name:"Cloud CDN"},
  {name:"Cloud DNS"},
  {name:"Cloud Load Balancing"},
  {name:"Cloud NAT"},
  {name:"Cloud Router"},
  {name:"Cloud VPN (HA)"},
  {name:"Network Service Tiers"},
  {name:"Network Telemetry"},
  {name:"Traffic Director"},
  {name:"Google Cloud Service Mesh"},
  {name:"Virtual Private Cloud"},
  {name:"VPC Service Controls"},
  {name:"Network Intelligence Center"},
  {name:"Google Cloud Game Servers"},
  {name:"Cloud IoT Core"},
  {name:"Access Transparency"},
  {name:"Binary Authorization"},
  {name:"Cloud Audit Logs"},
  {name:"Cloud Data Loss Prevention API"},
  {name:"Cloud HSM"},
  {name:"Cloud EKM"},
  {name:"Cloud IAM"},
  {name:"Cloud Identity"},
  {name:"Cloud Identity-Aware Proxy"},
  {name:"Cloud KMS"},
  {name:"Cloud Resource Manager"},
  {name:"Cloud Security Command Center"},
  {name:"Cloud Security Scanner"},
  {name:"Context-aware Access"},
  {name:"Event Threat Detection"},
  {name:"Managed Service for MS Azure"},
  {name:"Active Directory"},
  {name:"Secret Manager"},
  {name:"Security Key Enforcement"},
  {name:"Shielded VMs"},
  {name:"Titan Security Key"},
  {name:"VPC Service Controls"},
  {name:"Cloud APIs"},
  {name:"Cloud Billing API"},
  {name:"Cloud Billing"},
  {name:"Cloud Console"},
  {name:"Cloud Deployment Manager"},
  {name:"Cloud Mobile App"},
  {name:"Private Catalog"},
  {name:"Cloud Debugger"},
  {name:"Error Reporting"},
  {name:"Cloud Logging"},
  {name:"Cloud Monitoring"},
  {name:"Cloud Profiler"},
  {name:"Cloud Trace"},
  {name:"Transparent SLIs"},
  {name:"Cloud Build"},
  {name:"Cloud Code for IntelliJ"},
  {name:"Cloud Code for VS Code"},
  {name:"Cloud Code"},
  {name:"Cloud Scheduler"},
  {name:"Cloud SDK"},
  {name:"Cloud Shell"},
  {name:"Cloud Source Repositories"},
  {name:"Cloud Tasks"},
  {name:"Cloud Tools for Eclipse"},
  {name:"Cloud Tools for Visual Studio"},
  {name:"Container Analysis"},
  {name:"Container Registry"},
  {name:"Artifact Registry"},
  {name:"Gradle App Engine Plugin"},
  {name:"Maven App Engine Plugin"},
  {name:"BigQuery Data Transfer Service"},
  {name:"Cloud Data Transfer"},
  {name:"Google Transfer Appliance"},
  {name:"Migrate for Anthos"},
  {name:"Migrate for Compute Engine"},
  {name:"Migrate from Amazon Redshift"},
  {name:"Migrate from Teradata"},
  {name:"Storage Transfer Service"},
  {name:"VM Migration"},
  {name:"Cloud Foundation Toolkit"},
  {name:"API Analytics"},
  {name:"API Monetization"},
  {name:"Apigee API Platform"},
  {name:"Apigee Hybrid"},
  {name:"Apigee Sense"},
  {name:"Cloud Endpoints"},
  {name:"Cloud Healthcare API"},
  {name:"Developer Portal"},
  {name:"GCP Marketplace"},
  {name:"Directions API"},
  {name:"Distance Matrix API"},
  {name:"Geocoding API"},
  {name:"Geolocation API"},
  {name:"Maps Embed API"},
  {name:"Maps JavaScript API"},
  {name:"Maps SDK for Android"},
  {name:"Maps SDK for iOS"},
  {name:"Maps Static API"},
  {name:"Maps SDK for Unity"},
  {name:"Maps URLs"},
  {name:"Places API"},
  {name:"Places Library and Maps JS API"},
  {name:"Places SDK for Android"},
  {name:"Places SDK for iOS"},
  {name:"Roads API"},
  {name:"Street View Static API"},
  {name:"Street View Service"},
  {name:"Time Zone API"},
  {name:"Admin SDK"},
  {name:"AMP for Email"},
  {name:"Apps Script"},
  {name:"Calendar API"},
  {name:"Classroom API"},
  {name:"Cloud Search"},
  {name:"Docs API"},
  {name:"Drive Activity API"},
  {name:"Drive API"},
  {name:"Drive Picker"},
  {name:"Email Markup"},
  {name:"G Suite Add-ons"},
  {name:"G Suite Marketplace"},
  {name:"Gmail API"},
  {name:"Hangouts Chat Bots"},
  {name:"People API"},
  {name:"Sheets API"},
  {name:"Slides API"},
  {name:"Task API"},
  {name:"Vault API"},
  {name:"Cloud Firestore"},
  {name:"Cloud Functions for Firebase"},
  {name:"Cloud Storage for Firebase"},
  {name:"Crashlytics"},
  {name:"Firebase A/B Testing"},
  {name:"Firebase App Distribution"},
  {name:"Firebase Authentication"},
  {name:"Firebase Cloud Messaging"},
  {name:"Firebase Dynamic Links"},
  {name:"Firebase Extensions"},
  {name:"Firebase Hosting"},
  {name:"Firebase In-App Messaging"},
  {name:"Firebase Performance Monitoring"},
  {name:"Firebase Predictions"},
  {name:"Firebase Realtime Database"},
  {name:"Firebase Remote Config"},
  {name:"Firebase Test Lab"},
  {name:"Google Analytics for Firebase"},
  {name:"ML Kit for Firebase"},
  {name:"Google Cloud Home Page"},
  {name:"Google Cloud Blog"},
  {name:"Google Cloud Open Source"},
  {name:"GCP Medium Publication"},
  {name:"Apigee Blog"},
  {name:"Firebase Blog"},
  {name:"G Suite Developers Blog"},
  {name:"G Suite GitHub"},
  {name:"G Suite Twitter"},
  {name:"Google Cloud Certifications"},
  {name:"Google Cloud System Status"},
  {name:"Google Cloud Training"},
  {name:"Google Developers Blog"},
  {name:"Google Maps Platform Blog"},
  {name:"Google Open Source Blog"},
  {name:"Google Security Blog"},
  {name:"Kaggle Home Page"},
  {name:"Kubernetes Blog"},
  {name:"Regions and Network Manager"},



  {name:"Google Cloud TensorFlow"},
  {name:"Google Cloud Flutter Development"},
  {name:"Google Cloud Flutter Web and Firebase Authentication"},
  {name:"Google Cloud Dart Functions Framework"},
  {name:"Google Cloud Cloud Run"},
  {name:"Google Cloud Data Validation Tool"},
  {name:"Google Cloud BigLake"},
  {name:"Google Cloud Awwvision"},
  {name:"Google Cloud Apigee API Management"},
  {name:"Google Cloud Apigee X and Cloud Armor"},
  {name:"Google Cloud AppSheet App"},
  {name:"Google Cloud Spanner"},
  {name:"Google Cloud BigQuery Omni"},
  {name:"Google Cloud Video AI"},
  {name:"Google Cloud Vertex AI platform"},
  {name:"Google Cloud Bigtable"},
  {name:"Google Cloud Firebase Web"},



  {name:"Amazon Omics"},
  {name:"Amazon Simple Notification Service"},
  {name:"Apache MXNet on AWS"},
  {name:"AWS Application Migration Service (MGN)"},
  {name:"AWS Local Zones"},
  {name:"AWS Service Management Connector"},
  {name:"AWS SimSpace Weaver"},
  {name:"AWS Supply Chain (Preview)"},
  {name:"AWS Verified Access (Preview)"},
  {name:"AWS Wickr"},
  {name:"Amazon DataZone (Preview)"},
  {name:"Amazon Security Lake (Preview)"},
  {name:"Amazon Verified Permissions (Preview)"},
  {name:"AWS Application Composer (Preview)"},
  {name:"AWS Clean Rooms (Preview)"},



  {name:"Salesforce Sales Automation"},
  {name:"Salesforce Opportunity Management"},
  {name:"Salesforce Forecast Management"},
  {name:"Salesforce Revenue Cloud"},
  {name:"Salesforce Sales Engagement"},
  {name:"Salesforce Tableau Analytics"},
  {name:"Salesforce Order Management"},
  {name:"Salesforce Content Management"},


  {name:"Oracle Access Management"},
  {name:"Oracle Adaptive Query Optimization"},
  {name:"Oracle Billing and Revenue Management"},
  {name:"Oracle Blockchain Platform Service"},
  {name:"Orcale Data Mining"},
  {name:"Oracle Big Data Cloud Service"},
  {name:"Oracle Big Data Preparation Cloud Service"},
  {name:"Oracle Warehouse Management"},


  {name:"Managed Service for MS Azure"},
  {name:"Azure Bot Services"},
  {name:"Azure Cognitive Search"},
  {name:"Azure Databricks"},
  {name:"Azure Machine Learning"},
  {name:"Azure Open Datasets"},
  {name:"Azure Cognitive Services"},
  {name:"Azure Video Indexer"},
  {name:"Azure Form Recognizer"},
  {name:"Azure Immersive Reader"},
  {name:"Azure Metrics Advisor"},
  {name:"Azure Percept Preview"},
  {name:"Azure Applied AI Services"},
  {name:"Azure OpenAI Service Preview"},
  {name:"Azure Analysis Services"},
  {name:"Azure Data Explorer"},
  {name:"Azure Data Factory"},
  {name:"Azure confidential ledger"},
  {name:"Azure DevOps"},
  {name:"Azure Arc"},
  {name:"Azure IoT Edge"},
  {name:"Azure ExpressRoute"},
  {name:"Azure Stack HCI"},
  {name:"Azure Sentinel"},
  {name:"Azure RTOS"},
  {name:"Azure Maps"},
  {name:"Azure Sphere"},
  {name:"Azure Bastion"},
  {name:"Azure DDoS Protection"},
  {name:"Azure Firewall"},
  {name:"Azure SignalR Service"},
  {name:"Azure Web PubSub"},
  {name:"Azure Data Lake Storage"},
  {name:"Azure Data Lake Storage Gen1"},
  {name:"Azure Data Share"},
  {name:"Azure Stream Analytics"},
  {name:"Azure Synapse Analytics"},
  {name:"Azure CycleCloud"},
  {name:"Azure Quantum"},
  {name:"Azure Spot Virtual Machines"},
  {name:"Azure Spring Apps"},
  {name:"Azure VMware Solution"},
  {name:"Azure VM Image Builder"},
  {name:"Azure Kubernetes Service(AKS)"},
  {name:"Azure Functions"},
  {name:"Azure Container Instances"},
  {name:"Azure Service Fabric"},
  {name:"Azure Red Hat OpenShift"},
  {name:"Azure Purview"},
  {name:"Azure Virtual Desktop"},
  {name:"Azure Kubernetes Fleet Manager"},
  {name:"Azure Cosmos DB"},

]

const TECHNOLOGIES = NEWTECHNOLOGIES.filter((a,b) => NEWTECHNOLOGIES.indexOf(a) === b)
export default TECHNOLOGIES;
