const ALLJOBTITLES = ["AWS Cloud Practitioner",
"AWS Developer",
"AWS SysOps Administrator",
"AWS Solutions Architect",
"AWS DevOps Engineer",
"AWS Solutions Architect",
"AWS Big Data Engineer",
"AWS Big Data Consultant",
"AWS Advanced Networking ",
"AWS Security Engineer",
"AWS Alexa Skill Builder ",
"AWS ML Engineer",
"AWS Cloud Application Architect",
"AWS Cloud Application Developer",
"AWS Cloud Infrastructure Architect",
"AWS Cloud Systems Administrator",
"AWS Data Scientist",
"AWS Consultant",
"AWS Cloud Senior Technology Consultant",
"AWS Infrastructure Consultant",
"AWS Senior Consultant",
"Cloud Infrastructure Consultant",
"AWS Cloud Strategy & Architect Consultant",
"Technical Solution Architect -",
"Senior Cloud Engineer",
"AWS Security Consultant",
"AWS Cloud Architect",
"NetSuite Administrator",
"NetSuite Business Analyst",
"NetSuite Developer",
"NetSuite Project Manager",
"NetSuite Consultant",
"NetSuite Finance",
"NetSuite Systems Manager",
"NetSuite Architect",
"NetSuite Advanced Financials",
"NetSuite Advanced Inventory",
"NetSuite Advanced Order Management",
"NetSuite Advanced Procurement",
"NetSuite Advanced Software",
"NetSuite Contract Renewals",
"NetSuite Demand Planning",
"NetSuite Financial Planning",
"NetSuite Fixed Asset Management",
"NetSuite Incentive Compensation",
"NetSuite Job Costing",
"NetSuite Manufacturing WIP & Routings",
"NetSuite Multi-Book Accounting",
"NetSuite OneWorld",
"NetSuite Premium Customer Center",
"NetSuite Premium Datacenter Tiers",
"NetSuite Project Management",
"NetSuite Resource Allocation",
"NetSuite Revenue Recognition",
"NetSuite Suite Analytics Connect",
"NetSuite SuiteCommerce Advanced",
"NetSuite SuiteCommerce SiteBuilder",
"NetSuite Warehouse Management System",
"NetSuite Warehouse Management System Lite",
"NetSuite Work Orders & Assemblies",
"Salesforce Consultant ",
"Salesforce Lightning Consultant",
"Salesforce Architect",
"Salesforce Developer",
"Salesforce Administrator",
"Salesforce Advanced Administrator",
"Salesforce Data Architecture and Management Designer",
"Salesforce Sharing and Visibility Designer",
"Salesforce Platform Developer ",
"Salesforce App Builder",
"Salesforce Technical Architect",
"Salesforce Application Architect",
"Salesforce Systems Architect",
"Salesforce Community Cloud Consultant",
"Salesforce Mobile Solutions Architecture Designer",
"Salesforce Development Lifecycle and Deployment Designer",
"Salesforce Identity and Access Management Designer",
"Salesforce Integration Architecture Designer",
"Salesforce Sales Cloud Consultant",
"Salesforce Service Cloud Consultant",
"Salesforce Marketing Cloud Email Specialist",
"Salesforce Marketing Cloud Consultant",
"Salesforce Mobile Connect Expert",
"Salesforce Pardot ",
"Salesforce Data Analyst",
"Salesforce Einstein Analytics",
"MuleSoft Developer",
"Salesforce CPQ Consultant",
"Salesforce DX Consultant",
"Salesforce Business Analyst",
"Salesforce Solutions Architect",
"Salesforce Consultant - Functional",
"Salesforce Consultant - Technical",
"Salesforce Developer / Programmer",
"Salesforce Consultant Administrator",
"Salesforce Technical Architect",
"Solution Architect",
"Oracle eBusiness Suite Consultant",
"Oracle EBS Consultant",
"Oracle EBS Functional Analyst",
"Oracle EBS Technical Analyst",
"Oracle HCM Consultant",
"Oracle Associate",
"Oracle Professional",
"Oracle Master",
"Oracle Expert",
"Oracle Specialist",
"Oracle Forms Developer",
"Oracle Reports Developer",
"Oracle Global Human Resources Cloud Implementation Specialist",
"Oracle Benefits Cloud Implementation Specialist",
"Oracle Benefits Cloud Implementation Specialist",
"Oracle Talent Management Cloud Implementation Specialist",
"Oracle Time and Labor Cloud Implementation Specialist",
"Oracle Financials Cloud: General Ledger Implementation Specialist",
"Oracle Financials Cloud: Payables Implementation Specialist",
"Oracle Financials Cloud: Receivables Implementation Specialist",
"Oracle Project Portfolio Management Cloud Implementation Specialist",
"Oracle Procurement Cloud Implementation Specialist",
"Oracle Planning and Collaboration Cloud Implementation Specialist",
"Oracle Inventory Cloud Implementation Specialist",
"Oracle Cost Management Cloud Implementation Specialist",
"Oracle Configurator Cloud Implementation Specialist",
"Oracle Pricing Cloud Implementation Specialist",
"Oracle Order Management Cloud Order to Cash Implementation Specialist",
"Oracle Transportation Management Cloud Service Implementation Specialist",
"Oracle Warehouse Management Cloud Implementation Specialist",
"Oracle Database 12c Administrator",
"Oracle Expert, Oracle Database 12c: RAC and Grid Infrastructure Administrator",
"Oracle Database Performance and Tuning Implementation Specialist",
"Oracle Real Application Clusters 12c Implementation Specialist",
"Oracle Expert, Oracle Database Performance Management and Tuning",
"Oracle Database 12c Implementation Specialist",
"Oracle Database Foundations Junior Associate",
"Oracle Database 12c Administrator Associate",
"Oracle Database 12c Administrator Professional",
"Oracle Database 12c Maximum Availability Expert",
"Oracle Database 12c Maximum Availability Master",
"Oracle Expert, Oracle Database 12c: Data Guard Administrator",
"Oracle Database 12c Administrator ",
"Oracle Database 10g",
"Oracle Apps DBA",
"Oracle Database 12c Administrator Master",
"Oracle Database Security",
"Oracle Database SQL",
"Oracle PL/SQL Developer",
"Oracle Workflow Developer",
"Oracle Database PL/SQL Developer",
"Google Cloud Infrastructure Architect",
"GCP Professional Cloud Architect",
"GCP Data Engineer",
"Google Cloud Administrator",
"Google Cloud Consultant",
"Google Cloud Engineer",
"Google Cloud Network Architect",
"Google Cloud Developer",
"Google Cloud DevOps Engineer",
"GCP Cloud Architect - Technical",
"GCP Systems Administrator",
"Azure Architect",
"Azure Cloud Engineer",
"MS Azure Consultant",
"MS Azure Platform Infrastructure Architect",
"MS Azure Professional Cloud Architect",
"MS Azure Data Engineer",
"MS Azure Cloud Administrator",
"MS Azure Platform Consultant",
"MS Azure Platform Engineer",
"MS Azure Cloud Network Architect",
"MS Azure Cloud Developer",
"MS Azure DevOps Engineer",
"MS Azure Cloud Architect ",




"Salesforce DevOps lead",
"Salesforce Business Analyst",
"Salesforce Consultant",
"Salesforce Technical Consultant",
"Salesforce Solution Consultant",
"Azure Administrator Associate",
"Microsoft Certified Azure Developer Associate",
"Cloud software engineer",
"Cloud sales executive",
"Cloud engineer",
"Cloud systems administrator",
"Cloud systems engineer",
"Cloud network engineer",
"Cloud product manager",
"Cloud architect",
"Blockchain Developer",
"Microsoft Azure Architect Design",
"AWS Developer Associate",
"AWS SysOps Associate",
"AWS Solutions Architect",
"Salesforce Solution Architect",
"Salesforce Administrator",
"Salesforce Platform Manager", 
"Salesforce Project Manager",
"Azure DevOps Engineer",
"Azure Security Engineer",
"MS Azure Data Scientist",
"Azure AI Engineer",
"Azure Data Engineer",
"Cloud Technical Consultant",
]

const JOBTITLES = ALLJOBTITLES.filter((a,b) => ALLJOBTITLES.indexOf(a) === b)
export default JOBTITLES;
